### ISSUE TITLE
Youtube/Odysee links lost from EEVblog RSS feed

### ISSUE THREAD

**Issue by kriswilk** [slurdge/goeland#43]
As I was migrating feeds into goeland, I noticed this one seems to lose its video links:

https://www.eevblog.com/feed/

Probably a consequence of how they're referenced in the feed content (the src of an iframe, within a figure). Any way to preserve these?

**Comment by slurdge** [comment]
Yes this is due to the fact that goeland sanitize the feed before applying filters. I could specifically allow some URLs (look at this issue: https://github.com/microcosm-cc/bluemonday/issues/120) but I think it's somewhat not a good solution.

**Comment by slurdge** [comment]
I'm looking to have a special func on iframes what would extract the link on `retrieve` filter.

**Comment by slurdge** [comment]
I have a current implementation that works but I really don't like it, basically, I do a special processing in order to extract iframe links.

I plan to completely change that with the following:

1. Introduce a `--unsafe-no-sanitize-filter` command line option along with a configuration file option `unsafe-no-sanitize-filter`.
2. Sanitizing will be moved to a first and special filter (I still have to see if there are no processing before).
3. Sanitizing filter will be made available as a regular filter.

That way, it should be possible to download eevblog RSS, do no sanitation, replace the <iframe>, do sanitation and have a proper email.

@kriswilk By the way, the links are for the embedded version of the videos, so it's not a direct link to youtube.

**Comment by slurdge** [comment]
I have made the changes in order to not "sanitize" the input and it does work. However it seems that most (all ?) email clients are blocking iframes anyway. @kriswilk Do you have a special email client in mind ?

**Comment by slurdge** [comment]
v0.11.0 should be good for this issue.
